language: node_js
node_js:
- lts/*
- node
env:
  matrix:
  - REDUX_SAGA_VERSION=^0.11.1
  - REDUX_SAGA_VERSION=^1.0.0
before_script:
  - npm install redux-saga@${REDUX_SAGA_VERSION}
jobs:
  include:
    - stage: deploy
      if: branch = master
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
